/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.Gui;

import com.sun.rowset.internal.Row;
import java.io.IOException;
import edu.esprit.Gui.InterfaceGlobale;
import edu.esprit.dao.ClientDAO;
import javax.swing.JOptionPane;
/**
 *
 * @author Hajoura
 */
public class GestionClient extends javax.swing.JPanel {
    public int mot ;
    //  private final InterfaceGlobale j;

    /**
     * Creates new form GestionClient
     */
    public GestionClient(){
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        bt_supprimerclient = new javax.swing.JButton();
        btAjouterClient = new javax.swing.JButton();

        jTable2.setModel(new AffichageClients());
        jScrollPane2.setViewportView(jTable2);

        bt_supprimerclient.setText("Supprimer client");
        bt_supprimerclient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_supprimerclientActionPerformed(evt);
            }
        });

        btAjouterClient.setText("Ajouter client");
        btAjouterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAjouterClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_supprimerclient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAjouterClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btAjouterClient)
                .addGap(18, 18, 18)
                .addComponent(bt_supprimerclient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAjouterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAjouterClientActionPerformed
        new AjoutCompteClient().setVisible(true);
    }//GEN-LAST:event_btAjouterClientActionPerformed

    private void bt_supprimerclientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_supprimerclientActionPerformed
            
    }//GEN-LAST:event_bt_supprimerclientActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAjouterClient;
    private javax.swing.JButton bt_supprimerclient;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
